config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :phone_number, uniqueness: true, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :content, length: { minimum: 1 }
  validates :rating, inclusion: { in: [1, 2, 3, 4, 5] }
end

# A review must have a parent restaurant.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
    before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
    def index
      @restaurants = Restaurant.all
    end

   def new
     @restaurant = Restaurant.new
   end

   def create
      @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
      redirect_to restaurants_path
    else
      render :new
    end
   end

  def show
  end

  def edit
  end
  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurants_path
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to restaurants_path
  end

  private
  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
  _form.html.erb

  <%= simple_form_for restaurant do |r| %>
    <%= r.input :name %>
    <%= r.input :address %>
    <%= r.input :category %>
    <%= r.input :phone_number %>
    <%= r.submit %>
  <% end %>

app/views/restaurants/edit.html.erb
edit.html.erb


<div class="container">
  <%= render "form", restaurant: @restaurant %>
</div>

<%= link_to "< Back", restaurants_path, class:" btn btn-light" %>

app/views/restaurants/index.html.erb
<h1>restaurants index.html</h1>
<%= link_to 'Add a restaurant!', new_restaurant_path, class:"btn btn-primary" %>

<%  @restaurants.each do |restaurant| %>
<h2> <%= link_to restaurant.name, restaurant_path(restaurant) %> </h2>
<p><%= restaurant.category %></p>
<p><%= restaurant.address %></p>
<p><%= restaurant.phone_number %></p>
<%= link_to "Modifier", edit_restaurant_path(restaurant), class:"btn btn-primary" %>
<%= link_to "Supp", restaurant_path(restaurant), method: :delete, class:"btn btn-danger" %>
<% end %>

app/views/restaurants/new.html.erb
<h1>  new.html.erb </h1>

<div class="container">
  <%= render "form", restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
show.html.erb

<h1>Restaurants#show</h1>

<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>


<%= link_to "< Back", restaurants_path, class:" btn btn-light" %>